
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helloworlds.schooldevops.com
spec:
  group: schooldevops.com
  names:
    kind: HelloWorld
    plural: helloworlds
    singular: helloworlds
    shortNames:
      - hw
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                morningHeloWorld:
                  type: string
                noonHelloWorld:
                  type: string
                eveningHelloWorld:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer