apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: storage
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: my-storage
  resources:
    requests:
      storage: 200Mi
