apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: mynginx
      image: nginx
      volumeMounts:
      - mountPath: "/usr/nginx/html"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: my-pvc
