apiVersion: v1
kind: Service
metadata:
  name: mariadb-nodeport
  namespace: storage
  labels:
    app: mariadb
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
    - nodePort: 32306
      protocol: TCP
      port: 3306

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-storage
  namespace: storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-statefulset-mariadb-0
  namespace: storage
spec:
  storageClassName: "my-storage"
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /Users/1111489/Documents/01.STUDY/KUBE/local-storage
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/hostname"
          operator: "In"
          values:
          - GLW4XPMQ2X

---
 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: storage
spec:
  replicas: 1
  serviceName: mariadb
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
          - name: tpc
            protocol: TCP
            containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
        volumeMounts:
          - name: mariadb-data
            mountPath: /var/lib/mariadb
  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
        namespace: storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
      # volumes:
      # - name: mariadb-data
      #   persistentVolumeClaim:
      #     claimName: my-pvc
