apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
     app: nginx
     type: front-end
spec:
  template:
     metadata:
       name: nginx
       labels: 
         app: nginx
         type: front-end
     spec:
         containers:
           - name: nginx
             image: nginx
           - name: redis
             image: redis
  replicas: 3
  selector:
    matchLabels:
      type: front-end