apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    creationTimestamp: "2022-03-31T06:35:02Z"
    generation: 1
    labels:
      app: nginx
      type: front-end
    name: nginx
    namespace: default
    resourceVersion: "675086"
    uid: 99eb759b-2600-4270-88e8-f3d6c99a3cc0
  spec:
    replicas: 5
    selector:
      matchLabels:
        type: front-end
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nginx
          type: front-end
        name: nginx
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - image: redis
          imagePullPolicy: Always
          name: redis
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    fullyLabeledReplicas: 3
    observedGeneration: 1
    readyReplicas: 3
    replicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
